### ISSUE TITLE
Export default ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/is-any-array#2]
I'm migrating this project to es6 module but I wonder if I should export default or just export.

If I export as default it means that I would need to use the syntax
```const isAnyArray = require('is-any-array').default; ```
and add the 'default' at the end ?

This does not look very nice and I would then prefer
```const {isAnyArray} = require('is-any-array'); ```

https://github.com/cheminfo/is-any-array/blob/aad26d45faec79966dc49f7221e3b8e331d64fa0/src/index.js#L3-L5

@targos I guess it is not the first time I ask you this question ...

**Comment by targos** [comment]
If you build with rollup and export as default, you will be able to `require('is-any-array')`.
The question to ask is: will the library always have only a default export and no other? If the answer is yes, you can export as default. If it's no, or you're not sure, use a named export.
